apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: mk-dl-bot
spec:
  selector:
    matchLabels:
      app: mk-dl-bot
      service: db
  serviceName: db
  template:
    metadata:
      labels:
        app: mk-dl-bot
        service: db
    spec:
      containers:
        - image: postgres:alpine
          name: db
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: secret
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: db-data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
