apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: mk-dl-bot
spec:
  selector:
    app: mk-dl-bot
    service: db
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 5432
