apiVersion: v1
kind: Service
metadata:
  name: tg-service
  namespace: mk-dl-bot
spec:
  selector:
    app: mk-dl-bot
    service: tg
  type: ClusterIP
  ports:
  - name: tg
    protocol: TCP
    port: 8081
