apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mk-dl-bot
    service: bot
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mk-dl-bot
      service: bot
  template:
    metadata:
      labels:
        app: mk-dl-bot
        service: bot
    spec:
      containers:
        - image: mykola2312/mk-dl-bot:latest
          name: bot
          envFrom:
            - secretRef:
                name: secret